name: Streamlit Medical Report Analyzer CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit google-generativeai groq Pillow PyPDF2

      - name: Create .streamlit/secrets.toml
        run: |
          mkdir -p ~/.streamlit
          echo "\
[general]  
email = \"you@example.com\"

[api_keys]
GEMINI_API_KEY = '${{ secrets.GEMINI_API_KEY }}'
GROQ_API_KEY = '${{ secrets.GROQ_API_KEY }}'
          " > ~/.streamlit/secrets.toml

      - name: Run basic Streamlit test
        run: |
          streamlit run your_script_name.py --server.headless true &
          sleep 15
          curl -I http://localhost:8501 || echo "Streamlit app did not respond"

      - name: Cleanup
        run: |
          pkill -f streamlit || true
