name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use a compatible Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Deploy to Streamlit Cloud
    - name: Deploy to Streamlit Cloud
      env:
        STREAMLIT_CLOUD_API_TOKEN: ${{ secrets.STREAMLIT_CLOUD_API_TOKEN }}
      run: |
        streamlit deploy .
